apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3
  namespace: 8673ceff-springboot-s3
spec:
  rules:
    - host: springboot-s3-8673ceff-s3-dev.development.krci-dev.cloudmentor.academy
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s3
                port:
                  number: 80