apiVersion: v1
kind: Service
metadata:
  name: s3
  namespace: 8673ceff-springboot-s3
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: springboot-s3
    app.kubernetes.io/name: springboot-s3
  type: ClusterIP